authors = ["William Herrera <wherrera@alahonua.com>"]
name = "ThreadSafeDicts"
uuid = "4239201d-c60e-5e0a-9702-85d713665ba7"
version = "0.0.1"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
